"""empty message

Revision ID: 8d16ae8adf76
Revises: 
Create Date: 2019-12-05 19:17:23.185789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d16ae8adf76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('game',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.Column('tried', sa.String(length=50), nullable=True),
    sa.Column('player', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['player'], ['user.username'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
