"""empty message

Revision ID: 97adb10b3d2e
Revises: 8d16ae8adf76
Create Date: 2019-12-05 22:35:50.726008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97adb10b3d2e'
down_revision = '8d16ae8adf76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('losses', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wins')
    op.drop_column('user', 'losses')
    # ### end Alembic commands ###
